name          'nrvale0-postfix'
version       '0.1.0'
source        'https://github.com/nrvale0/puppet-postfix'
author        'Nathan Valentine <nrvale0@gmail.com>, http://about.me/nrvale0'
license       'Apache 2.0'
summary       'Simple module to manage Postfix mail server'
description   ''
project_page  'https://github.com/nrvale0/puppet-postfix'

dependency 'puppetlabs/stdlib'
